apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  label:
    app: redis
spec:
  selector:
    app: redis
    role: master
    tier: backed
  replicas: 1
  template:
    metadata:
      lables:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: k8s.gcr.io/redis:e2e
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379